### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by JeftaDirksen** [SommerEngineering/MinecraftServerRCONSharp#1]
Hi SommerEngineering,

I've added the following line at the beginning of the internalSendMessage method:
if (!this.tcp.Connected) this.openConnection();

So when the connection to minecraft drops (minecraft restart) it will reconnect.
It works for me but i'm not sure if it is the "best"/correct solutions, but i thought i'll let you know.

Oh by the way, great project :+1: :)

Greets,

Jefta

**Comment by SommerEngineering** [comment]
Hey Jefta,

Thanks for your response. I have released the version 1.0.2 (on NuGet and on the releases page on GitHub) which contains this kind of auto-reconnection to the Minecraft server. The line you added is not a safe solution -- please just upgrade to version 1.0.2 for the stable solution.

Best regards,
Thorsten

**Comment by JeftaDirksen** [comment]
Thanks very much!
I'll update to the 1.0.2.

Jefta
